// <auto-generated />
using System;
using InfluencerMatch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfluencerMatch.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307054415_AddUserIdToCreator")]
    partial class AddUserIdToCreator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.BrandMention", b =>
                {
                    b.Property<int>("BrandMentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandMentionId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectionMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BrandMentionId");

                    b.HasIndex("BrandName");

                    b.HasIndex("CreatorId");

                    b.HasIndex("VideoId", "BrandName")
                        .IsUnique();

                    b.ToTable("BrandMentions");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CampaignId");

                    b.HasIndex("BrandId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.ChannelVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique();

                    b.ToTable("ChannelVideos");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CollaborationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("BrandUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<string>("CampaignTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("BrandUserId");

                    b.HasIndex("CreatorProfileId");

                    b.ToTable("CollaborationRequests");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Creator", b =>
                {
                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatorId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorTier")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSmallCreator")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<double?>("LanguageConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<long>("Subscribers")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VideoCount")
                        .HasColumnType("integer");

                    b.HasKey("CreatorId");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("CreatorTier");

                    b.HasIndex("IsSmallCreator");

                    b.HasIndex("Language");

                    b.HasIndex("Region");

                    b.HasIndex("Subscribers");

                    b.HasIndex("UserId");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorAnalytics", b =>
                {
                    b.Property<int>("CreatorAnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatorAnalyticsId"));

                    b.Property<double>("AvgComments")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgLikes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgViews")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("double precision");

                    b.HasKey("CreatorAnalyticsId");

                    b.HasIndex("CreatorId")
                        .IsUnique();

                    b.ToTable("CreatorAnalytics");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ChannelPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChannelUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorTier")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStatsUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Subscribers")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.Property<int>("VideoCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("CreatorTier");

                    b.HasIndex("EngagementRate");

                    b.HasIndex("Subscribers");

                    b.ToTable("CreatorChannels");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorGrowth", b =>
                {
                    b.Property<int>("GrowthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GrowthId"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Subscribers")
                        .HasColumnType("bigint");

                    b.HasKey("GrowthId");

                    b.HasIndex("CreatorId", "RecordedAt");

                    b.ToTable("CreatorGrowth");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorGrowthScore", b =>
                {
                    b.Property<int>("CreatorGrowthScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatorGrowthScoreId"));

                    b.Property<long>("BaselineSubscribers")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("GrowthCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GrowthRate")
                        .HasColumnType("double precision");

                    b.Property<long>("SubscriberDelta")
                        .HasColumnType("bigint");

                    b.HasKey("CreatorGrowthScoreId");

                    b.HasIndex("CreatorId")
                        .IsUnique();

                    b.HasIndex("GrowthRate");

                    b.ToTable("CreatorGrowthScores");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorProfile", b =>
                {
                    b.Property<int>("CreatorProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatorProfileId"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CreatorProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CreatorProfiles");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreId"));

                    b.Property<double>("AverageViews")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<double>("EngagementComponent")
                        .HasColumnType("double precision");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("double precision");

                    b.Property<double>("FrequencyComponent")
                        .HasColumnType("double precision");

                    b.Property<double>("GrowthComponent")
                        .HasColumnType("double precision");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<double>("SubscriberGrowthRate")
                        .HasColumnType("double precision");

                    b.Property<double>("UploadFrequency")
                        .HasColumnType("double precision");

                    b.Property<double>("ViewsComponent")
                        .HasColumnType("double precision");

                    b.HasKey("ScoreId");

                    b.HasIndex("CreatorId")
                        .IsUnique();

                    b.HasIndex("Score");

                    b.ToTable("CreatorScores");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Influencer", b =>
                {
                    b.Property<int>("InfluencerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InfluencerId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<string>("InstagramLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerPost")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("YouTubeLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InfluencerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Influencers");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.MatchResult", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchId"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<int>("InfluencerId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("MatchId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("InfluencerId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.VideoAnalytics", b =>
                {
                    b.Property<int>("VideoAnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideoAnalyticsId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("text");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("double precision");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VideoAnalyticsId");

                    b.HasIndex("BrandName");

                    b.HasIndex("CreatorId");

                    b.HasIndex("VideoType");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique();

                    b.ToTable("VideoAnalytics");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.VideoMetrics", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricId"));

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MetricId");

                    b.HasIndex("YoutubeVideoId", "RecordedAt");

                    b.ToTable("VideoMetrics");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.VideoViralScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreId"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EngagementMomentum")
                        .HasColumnType("double precision");

                    b.Property<double>("GrowthAcceleration")
                        .HasColumnType("double precision");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ViewsVelocity")
                        .HasColumnType("double precision");

                    b.Property<double>("ViewsVelocityRaw")
                        .HasColumnType("double precision");

                    b.Property<double>("ViralScore")
                        .HasColumnType("double precision");

                    b.HasKey("ScoreId");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.HasIndex("ViralScore");

                    b.ToTable("VideoViralScores");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.BrandMention", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.ChannelVideo", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.CreatorChannel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .HasPrincipalKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CollaborationRequest", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.User", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfluencerMatch.Domain.Entities.CreatorProfile", "Creator")
                        .WithMany("CollaborationRequests")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Creator", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorAnalytics", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorChannel", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.CreatorProfile", "CreatorProfile")
                        .WithMany("Channels")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorProfile");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorGrowth", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorGrowthScore", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorProfile", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorScore", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Influencer", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.User", "User")
                        .WithOne("InfluencerProfile")
                        .HasForeignKey("InfluencerMatch.Domain.Entities.Influencer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.MatchResult", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Campaign", "Campaign")
                        .WithMany("MatchResults")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfluencerMatch.Domain.Entities.Influencer", "Influencer")
                        .WithMany("MatchResults")
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Influencer");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Video", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.VideoAnalytics", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.VideoMetrics", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.ChannelVideo", "Video")
                        .WithMany("Metrics")
                        .HasForeignKey("YoutubeVideoId")
                        .HasPrincipalKey("YoutubeVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.VideoViralScore", b =>
                {
                    b.HasOne("InfluencerMatch.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .HasPrincipalKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("MatchResults");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.ChannelVideo", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorChannel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.CreatorProfile", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("CollaborationRequests");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.Influencer", b =>
                {
                    b.Navigation("MatchResults");
                });

            modelBuilder.Entity("InfluencerMatch.Domain.Entities.User", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("InfluencerProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
